# General
app.name=kib-rgs
app.url=https://v3.rgsplus.nl/
server.port=8099

# Server Errors
server.error.include-binding-errors=always
server.error.include-message=always

# MongoDB
spring.data.mongodb.uri=mongodb://rgsplus:rgsplus@ec2-34-243-173-125.eu-west-1.compute.amazonaws.com:27017/?directConnection=true&authSource=admin
spring.data.mongodb.database=kib-rgs
spring.main.allow-circular-references=true

# Mail
spring.mail.host=email-smtp.eu-west-1.amazonaws.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.username=AKIAZYIDRHJSE7WMXMXS
spring.mail.password=BEu6Va9nvK6dxz5o0/CzUB4ETVphpMI1ms6UuegpZbWh

keycloak.server=https://keycloak.rgsplus.nl
keycloak.realm=RGSplus
keycloak.client-id=admin-cli
keycloak.client-secret=Qeobii4jq4dsg8UW8JP60AA2so9xG8k1
keycloak.rgsplus-client-id=webapp

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://keycloak.rgsplus.nl/realms/RGSplus
